#include<iostream>
#include<string>
#include<map>
#include<set>
#include<queue>
#include<list>
#include<climits>
#include<cmath>
#include<stack>
#include<unordered_map>
#include<unordered_set>
#include<algorithm>
#include<vector>
#include<utility>
#include<bitset>
#include<functional>
#include<numeric>
#include<iterator>
#include<sstream>
#include<fstream>
#include<cstdlib>
#include<cstring>
#include<cstdio>
#include<ctime>
#include<cmath>
#include<cstdlib>

#include<tuple>
#include<array>
#include<regex>
using namespace std;